### ISSUE TITLE
有木有想法打包成docekr镜像，php环境实在不爽

### ISSUE THREAD

**Issue by muyiacc** [mxue12138/MKOnlineMusicPlayer#2]

**Comment by mxue12138** [comment]
参考该页面，https://hub.docker.com/_/php/tags?page=1&name=7.2-apache 或 https://hub.docker.com/_/php/tags?page=1&name=7.2-fpm-alpine3.12，映射端口和项目的目录到 docker 内就行

**Comment by kid9547** [comment]
> 参考该页面，https://hub.docker.com/_/php/tags?page=1&name=7.2-apache 或 https://hub.docker.com/_/php/tags?page=1&name=7.2-fpm-alpine3.12 ，映射端口和项目的目录到 docker 内就行

这个说法可能大佬一看就明白，但是作为小白了我研究了好几天，写下我的理解吧。

第一步：
这将在当前目录下创建一个名为MKOnlineMusicPlayer的文件夹，里面包含了项目的所有文件。

git clone https://github.com/mxue12138/MKOnlineMusicPlayer.git

第二步：
克隆仓库后，切换到项目目录：

cd MKOnlineMusicPlayer

第三步：
在项目的根目录中（即MKOnlineMusicPlayer文件夹内），创建一个名为docker-compose.yml的文件。

version: '3'

services:
  webapp:
    image: php:7.4-apache
    ports:
      - "4000:80"
    volumes:
      - ./:/var/www/html/

第四步：
 docker-compose up -d

第五步：
ip＋端口号4000，就可以访问了（如：192.168.1.2:4000）

**Comment by mxue12138** [comment]
> > 参考该页面，https://hub.docker.com/_/php/tags?page=1&name=7.2-apache 或 https://hub.docker.com/_/php/tags?page=1&name=7.2-fpm-alpine3.12 ，映射端口和项目的目录到 docker 内就行
> 
> 这个说法可能大佬一看就明白，但是作为小白了我研究了好几天，写下我的理解吧。
> 
> 第一步： 这将在当前目录下创建一个名为MKOnlineMusicPlayer的文件夹，里面包含了项目的所有文件。
> 
> git clone https://github.com/mxue12138/MKOnlineMusicPlayer.git
> 
> 第二步： 克隆仓库后，切换到项目目录：
> 
> cd MKOnlineMusicPlayer
> 
> 第三步： 在项目的根目录中（即MKOnlineMusicPlayer文件夹内），创建一个名为docker-compose.yml的文件。
> 
> version: '3'
> 
> services: webapp: image: php:7.4-apache ports: - "4000:80" volumes: - ./:/var/www/html/
> 
> 第四步： docker-compose up -d
> 
> 第五步： ip＋端口号4000，就可以访问了（如：192.168.1.2:4000）

写的不错，不过注意一点，如果需要下载功能，记得要替换容器内apache配置，参考 README.md [#必要配置](https://github.com/mxue12138/MKOnlineMusicPlayer?tab=readme-ov-file#%E5%BF%85%E8%A6%81%E9%85%8D%E7%BD%AE)

**Comment by kid9547** [comment]
> > > 参考该页面，https://hub.docker.com/_/php/tags?page=1&name=7.2-apache 或 https://hub.docker.com/_/php/tags?page=1&name=7.2-fpm-alpine3.12 ，映射端口和项目的目录到 docker 内就行
> > 
> > 
> > 这个说法可能大佬一看就明白，但是作为小白了我研究了好几天，写下我的理解吧。
> > 第一步： 这将在当前目录下创建一个名为MKOnlineMusicPlayer的文件夹，里面包含了项目的所有文件。
> > git clone https://github.com/mxue12138/MKOnlineMusicPlayer.git
> > 第二步： 克隆仓库后，切换到项目目录：
> > cd MKOnlineMusicPlayer
> > 第三步： 在项目的根目录中（即MKOnlineMusicPlayer文件夹内），创建一个名为docker-compose.yml的文件。
> > version: '3'
> > services: webapp: image: php:7.4-apache ports: - "4000:80" volumes: - ./:/var/www/html/
> > 第四步： docker-compose up -d
> > 第五步： ip＋端口号4000，就可以访问了（如：192.168.1.2:4000）
> 
> 写的不错，不过注意一点，如果需要下载功能，记得要替换容器内apache配置，参考 README.md [#必要配置](https://github.com/mxue12138/MKOnlineMusicPlayer?tab=readme-ov-file#%E5%BF%85%E8%A6%81%E9%85%8D%E7%BD%AE)

很感谢大佬的回复，其实我很快就看见回复了，但是为了搞懂这两句话，我又研究了2天，哈哈哈。但是我一直没有找到配置文件的路径，和我用docker部署有关系吗？我先是docker exec -it musicplayer2-webapp-1 sh    （我容器的名字是musicplayer2-webapp-1），里面的文件和下载的源码差不多，没有找到apache2.conf或者httpd.conf，也没有/etc/apache2/这样类似的路径

**Comment by mxue12138** [comment]
> > > > 参考该页面，https://hub.docker.com/_/php/tags?page=1&name=7.2-apache 或 https://hub.docker.com/_/php/tags?page=1&name=7.2-fpm-alpine3.12 ，映射端口和项目的目录到 docker 内就行
> > > 
> > > 
> > > 这个说法可能大佬一看就明白，但是作为小白了我研究了好几天，写下我的理解吧。
> > > 第一步： 这将在当前目录下创建一个名为MKOnlineMusicPlayer的文件夹，里面包含了项目的所有文件。
> > > git clone https://github.com/mxue12138/MKOnlineMusicPlayer.git
> > > 第二步： 克隆仓库后，切换到项目目录：
> > > cd MKOnlineMusicPlayer
> > > 第三步： 在项目的根目录中（即MKOnlineMusicPlayer文件夹内），创建一个名为docker-compose.yml的文件。
> > > version: '3'
> > > services: webapp: image: php:7.4-apache ports: - "4000:80" volumes: - ./:/var/www/html/
> > > 第四步： docker-compose up -d
> > > 第五步： ip＋端口号4000，就可以访问了（如：192.168.1.2:4000）
> > 
> > 
> > 写的不错，不过注意一点，如果需要下载功能，记得要替换容器内apache配置，参考 README.md [#必要配置](https://github.com/mxue12138/MKOnlineMusicPlayer?tab=readme-ov-file#%E5%BF%85%E8%A6%81%E9%85%8D%E7%BD%AE)
> 
> 很感谢大佬的回复，其实我很快就看见回复了，但是为了搞懂这两句话，我又研究了2天，哈哈哈。但是我一直没有找到配置文件的路径，和我用docker部署有关系吗？我先是docker exec -it musicplayer2-webapp-1 sh （我容器的名字是musicplayer2-webapp-1），里面的文件和下载的源码差不多，没有找到apache2.conf或者httpd.conf，也没有/etc/apache2/这样类似的路径

可以看看版本记录，然后点击对应的编译 Digest，里面的 layers 部分一般都有写配置文件信息之类的，[layers](https://hub.docker.com/layers/library/php/7.2-apache/images/sha256-77e5a326252f951aa557f48829973f67e8efde9c52f81ee4e4a5473a59a217d9?context=explore)，当前这个镜像的配置文件在 /etc/apache2/sites-available/000-default.conf，修改即可

**Comment by mxue12138** [comment]
> > > > > > 参考该页面，https://hub.docker.com/_/php/tags?page=1&name=7.2-apache 或 https://hub.docker.com/_/php/tags?page=1&name=7.2-fpm-alpine3.12 ，映射端口和项目的目录到 docker 内就行
> > > > > 
> > > > > 
> > > > > 这个说法可能大佬一看就明白，但是作为小白了我研究了好几天，写下我的理解吧。
> > > > > 第一步： 这将在当前目录下创建一个名为MKOnlineMusicPlayer的文件夹，里面包含了项目的所有文件。
> > > > > git clone https://github.com/mxue12138/MKOnlineMusicPlayer.git
> > > > > 第二步： 克隆仓库后，切换到项目目录：
> > > > > cd MKOnlineMusicPlayer
> > > > > 第三步： 在项目的根目录中（即MKOnlineMusicPlayer文件夹内），创建一个名为docker-compose.yml的文件。
> > > > > version: '3'
> > > > > services: webapp: image: php:7.4-apache ports: - "4000:80" volumes: - ./:/var/www/html/
> > > > > 第四步： docker-compose up -d
> > > > > 第五步： ip＋端口号4000，就可以访问了（如：192.168.1.2:4000）
> > > > 
> > > > 
> > > > 写的不错，不过注意一点，如果需要下载功能，记得要替换容器内apache配置，参考 README.md [#必要配置](https://github.com/mxue12138/MKOnlineMusicPlayer?tab=readme-ov-file#%E5%BF%85%E8%A6%81%E9%85%8D%E7%BD%AE)
> > > 
> > > 
> > > 很感谢大佬的回复，其实我很快就看见回复了，但是为了搞懂这两句话，我又研究了2天，哈哈哈。但是我一直没有找到配置文件的路径，和我用docker部署有关系吗？我先是docker exec -it musicplayer2-webapp-1 sh （我容器的名字是musicplayer2-webapp-1），里面的文件和下载的源码差不多，没有找到apache2.conf或者httpd.conf，也没有/etc/apache2/这样类似的路径
> > 
> > 
> > 可以看看版本记录，然后点击对应的编译 Digest，里面的 layers 部分一般都有写配置文件信息之类的，[layers](https://hub.docker.com/layers/library/php/7.2-apache/images/sha256-77e5a326252f951aa557f48829973f67e8efde9c52f81ee4e4a5473a59a217d9?context=explore)，当前这个镜像的配置文件在 /etc/apache2/sites-available/000-default.conf，修改即可
> 
> 再次感谢回复，我终于知道我为啥没有找到了，感谢提供思路。说一下我的问题，因为我没有什么编程基础，所以没搞明白，小白也可以借鉴一下。第一步还是docker exec -it musicplayer2-webapp-1 sh （我容器的名字是musicplayer2-webapp-1，替换成自己的容器名字），之前缺失的就是这第二步：现在的目录不是根目录需要键入“cd ..”，cd和..中间有空格，然后就可以看见etc文件夹了，然后进入可以看见apache2文件夹，最后的配置文件确实在 /etc/apache2/sites-available/000-default.conf。再说一下我怎么找到配置文件的，除了这个回复前，我想的是在群晖环境变量里面找文件的，里面是有一个APACHE CONFDIR:=/etc/apache2，而且我通过gpt知道了配置文件多半在apache2下面，所以找了文件，文件夹下面有两个配置文件，其中000-default.conf就是了。部署这个项目主要还是学习，再次感谢大佬。

好的，代码我已经更新了，你可以看看 [#docker](https://github.com/mxue12138/MKOnlineMusicPlayer#docker)，另外我发现直接部署会有问题，因为 php 7.2-apache 这个镜像缺少 headers 模块，我在命令加上了，你可以参考 docker-compose.yml
